import {rollDice} from "@/utilities";

const bm_table8= [
    "Potion of Clairaudience",
    "Canopic Jars (Broken)",
    "Runic Tablet",
    "Magical Scarab (Decorative Amulet)",
    "Rope of Climbing",
    "Grateful Adventurer in stasis",
    "Scroll: Ward Against Lycanthropes",
    "Adventurer in Stasis (Doppelganger)",
    "Gold Bracelets",
    "Gem: Amber",
    "Runic Tablet",
    "Terra Cotta Canopic Jars (1d4)",
    "Potion of Climbing",
    "Green Slime*",
    "Scroll: Ward Against Magic",
    "Ochre Jelly*",
    "Magical Scarab (Gemstone)",
    "Wand of Fire Balls",
    "Silver Figurine",
    "Gem: Jade",
    "Rot Pudding*",
    "Potion of Strength",
    "Silver Earrings",
    "Glass Canopic Jars (1d4)",
    "Runic Tablet",
    "Bag of Devouring",
    "Magical Scarab (Cursed)",
    "Scroll: Ward Against Elementals",
    "Staked Vampire*",
    "Gold Signet Ring",
    "Gem: White Pearl",
    "Thief in Stasis (Wererat)*",
    "Scroll: 2 Random Magic-User Spells",
    "Silver Canopic Jars (1d4)",
    "Potion of Gaseous Form",
    "Magical Scarab (Decorative Amulet)",
    "Dust of Sneezing and Choking",
    "Runic Tablet",
    "Iron Statue*",
    "Strangely Preserved Lizardman",
    "Magical Scarab (Gemstone)",
    "Emerald Headdress",
    "Potion of Healing",
    "Runic Tablet",
    "Ointment of Healing",
    "Gem: Black Pearl",
    "Scroll: 2 Random Cleric Spells",
    "Electrum Canopic Jars (1d4)",
    "Perfumed Oil",
    "Runic Tablet",
    "Gem: Garnet (Red)",
    "Scroll: 3 Random Magic-User Spells",
    "Gold Scarab",
    "Barrow Ghast*",
    "Potion of Clairvoyance",
    "Gold Canopic Jars (1d4)",
    "Wand of Cold",
    "Pair of Small Gold Couchant Jackals",
    "Head of a Gold Scepter",
    "Platinum Ankh",
    "Barrow Mummy",
    "Potion of Sweetwater",
    "Empty Burial Shroud",
    "Runic Tablet",
    "Tome of Stealth",
    "Scroll: 3 Random Cleric Spells",
    "Platinum Canopic Jars (1d4)",
    "Basket of Petrified Fruit",
    "Gold Scarab",
    "Gem: Chrysoberyl",
    "Mummy*",
    "Silver Scarab",
    "Two Electrum Urns",
    "Scroll: 4 Random Magic-User Spells",
    "Gold and Ivory Canopic Jars (1d4)",
    "Runic Tablet",
    "Weapon +2 (Referee’s Discretion)",
    "Gem: Smoky Quartz",
    "Potion of Delusion",
    "Clockwork Cobra*",
    "Broken Black Urn",
    "Runic Tablet",
    "Silver Canopic Jars (1d4)",
    "Clockwork Scorpion",
    "Potion of Extra-Healing",
    "Wight*",
    "Silver Scarab",
    "Barrow Wight*",
    "Bottle of Ancient Wine",
    "Gem: Jasper (Blue)",
    "Mummified Jackal",
    "Wraith*",
    "Scroll: 4 Random Cleric Spells",
    "Runic Tablet",
    "Electrum Canopic Jars (1d4)",
    "Potion of Extra-Healing",
    "Platinum Scarab",
    "Vampire*",
    "Mithril Fleece (Cure Disease and Heal 1/week)",
    "Hand Axe +4 Dwarven Thrower"
];
// need to maintain this list since every entry is found only once.
(function (){
    if(!localStorage.getItem('bm_table8')) {
        localStorage.setItem('bm_table8', JSON.stringify(bm_table8));
    }
})();

export function generateSarcophagusContents(){
    let result,
        bm_copy = JSON.parse(localStorage.getItem('bm_table8')),
        index = rollDice(1, bm_copy.length).total - 1;

    result = bm_copy[index];

    bm_copy.splice(index, 1);

    localStorage.setItem('bm_table8', JSON.stringify(bm_copy));

    return result;
}
