import {rollDice} from "@/utilities";

const bm_table3 = [
    "A statue of a terrible gargoyle.",
    "The smell of burning garbage.",
    "Rubble piled into a pyramid in one corner.",
    "A strong gust of wind extinguishes torches.",
    "A helm with head and expression of horror.",
    "A large pile of bone and decaying flesh.",
    "A sack of weevil-infested biscuits.",
    "Footprints, clawed.",
    "A statue of a paladin, defaced.",
    "Several adventurer corpses piled near wall.",
    "Body of a cleric adventurer, 50% equipped.",
    "Polished skulls setting on a table.",
    "A pile of dead, half-eaten rats.",
    "A chalk drawing of several constellations.",
    "Indiscernible shouting, very distant.",
    "The slamming of a door in the distance.",
    "Rusted cauldron with rotten teeth inside.",
    "An altar with fresh blood.",
    "A strong gust of wind extinguishes torches.",
    "Puddles of scummy water.",
    "Rubble piled into a pyramid.",
    "Human teeth, yellowed (1d20).",
    "The smell of burning oil.",
    "Statue head, chipped beyond recognition.",
    "A pool of rank water and the smell of mold.",
    "Statue of St. Ygg, defaced and knocked over.",
    "Clanging swords, then silence.",
    "Body of an elf adventurer, 50% equipped.",
    "A large pile of bone and decaying flesh.",
    "Body of a dwarf adventurer, 50% equipped.",
    "A sinister human cackle.",
    "A sudden thud, then silence.",
    "Several adventurer corpses piled near wall.",
    "Stone grinding on stone in the distance.",
    "A very loud hissing sound, very far off.",
    "A low snarling noise from behind.",
    "A path of dried-up bread crumbs at a wall.",
    "A strong gust of wind extinguishes torches.",
    "Painting of a red arrow: “Go this way.”",
    "A phantom appears with cryptic message.",
    "Floor coated with flour. No prints (yet).",
    "A helm with head and expression of horror.",
    "Body of a halfling adventurer, 50% equipped.",
    "A strong gust of wind extinguishes torches.",
    "A sudden thud, then silence.",
    "A very loud hissing sound, very far off.",
    "Stone grinding on stone in the distance.",
    "Body of a M-U adventurer, 50% equipped.",
    "Map shows area (& secret doors) in 40' radius.",
    "A scratching noise, just beyond a random wall.",
    "Footprints, barefoot.",
    "Wall broken, with rune inscribed beneath.",
    "Table with dried up tongues left on it.",
    "Row of spiked adventurer heads.",
    "Death screams, then silence.",
    "Rusted cauldron with rotten teeth inside.",
    "Row of spiked adventurer heads.",
    "Receding torchlight ahead of the party.",
    "A pool of rank water and the smell of mold.",
    "The sound of rapidly beating insect wings.",
    "Stone grinding on stone in the distance.",
    "Handprint made in dried blood.",
    "A strong gust of wind extinguishes torches.",
    "A pool of rank water and the smell of mold.",
    "Stone grinding on stone in the distance.",
    "Footprints, booted.",
    "The slamming of a door in the distance.",
    "A strong gust of wind extinguishes torches.",
    "Footprints, clawed.",
    "Air suddenly becomes cool for 1d4 turns.",
    "An altar with fresh blood.",
    "A chalk drawing of several constellations.",
    "A hammer in the distance \"Tap-tom, tom-tap.\"",
    "An altar with a pile of bones, gnawed.",
    "An obelisk, broken.",
    "A pile of dead, half-eaten rats.",
    "3 adventurers impaled against wall.",
    "A path of dried-up bread crumbs stops at wall.",
    "A rat carcass, completely flattened.",
    "Footprints, barefoot.",
    "The sound of a door opening slowly.",
    "A rat carcass, completely flattened.",
    "A sack of weevil-infested biscuits.",
    "Partial collapse.",
    "Stones piled over human body with sword.",
    "Bucket helmet with head.",
    "Necklace of dried humanoid ears.",
    "Tattered black burial robes in a pile.",
    "A pouch with spell components.",
    "25 feet of rope.",
    "A pouch with 5 darts.",
    "Wooden holy symbol.",
    "A vial of holy water.",
    "A Dagger +1.",
    "A scroll: 1 MU spell.",
    "Chalk marks on the walls.",
    "Air suddenly becomes warm for 1d4 turns.",
    "A broken compass.",
    "Referee’s Choice.",
    "Referee’s Choice."
]
export function randomDungeonDressing(){
    return bm_table3[rollDice(1, 100).total-1];
}
